apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  labels:
    app: blog-service
spec:
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
      - name: blog-service
        image: 802564302645.dkr.ecr.ap-southeast-1.amazonaws.com/blog-service:error
#        image: blog-service:m1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_CONNNECTION_URL
          valueFrom:
            configMapKeyRef:
                name: mongo-config
                key: MONGO_CONNNECTION_URL
        - name: MONGO_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
                name: mongo-config
                key: MONGO_DATABASE_NAME
        - name: MONGO_COLLECTION_NAME
          valueFrom:
            configMapKeyRef:
                name: mongo-config
                key: MONGO_COLLECTION_NAME
