apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    blueGreen: 
      activeService: blue-green-rollouts-demo
      previewService: blue-green-rollouts-demo-preview
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.version | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.container.port }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blogs-env