apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-preview
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: http
    name: http
  selector:
    app: {{ .Values.name }}
#  type: {{ .Values.service.type }}