apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: nocnoc-key-sign-policy
spec:
  images:
  - glob: "*"
  authorities:
  - name: nocnoc-key
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvakoEh6E8DyIjLXFDkMakQYDE3tU
        Kd6sv+RCcBbWxvSeZHPxONq2CTSqdYp2B2kmgur9r1jaNwa0M/CbvGzWlQ==
        -----END PUBLIC KEY-----