apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-blogs-env
  labels:
    app: {{ .Release.Name }}-blogs-service
data:
  MONGO_CONNNECTION_URL: {{ .Values.app_env.mongo_url }}
  MONGO_DATABASE_NAME: {{ .Values.app_env.mongo_db_name  }}
  MONGO_COLLECTION_NAME: {{ .Values.app_env.mongo_collection_name }}